# Generated by Django 3.1.4 on 2020-12-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EducaUB', '0003_tb_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_estudante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_atual', models.TextField(max_length=255)),
                ('id_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducaUB.tb_escola')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducaUB.tb_pessoa')),
            ],
        ),
    ]
