# Generated by Django 3.1.4 on 2020-12-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EducaUB', '0004_tb_estudante'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_classe', models.TextField(max_length=255)),
                ('nome_materia', models.TextField(max_length=255)),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducaUB.tb_professor')),
            ],
        ),
        migrations.CreateModel(
            name='tb_administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducaUB.tb_pessoa')),
            ],
        ),
    ]
